[build]
  command = "npm ci && ROLLUP_SKIP_NODE_RESOLVE=true npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google.com https://apis.google.com https://cdn.gpteng.co https://*.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://accounts.google.com https://*.gstatic.com https://fonts.googleapis.com; img-src 'self' data: https: blob:; frame-src 'self' https://accounts.google.com https://*.google.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://accounts.google.com https://apis.google.com https://*.gstatic.com; font-src 'self' https://*.gstatic.com https://fonts.gstatic.com data:; worker-src 'self' blob: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; object-src 'none';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 