[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google.com https://accounts.google.com https://apis.google.com https://cdn.gpteng.co https://*.gstatic.com; style-src 'self' 'unsafe-inline' https://accounts.google.com https://*.gstatic.com; img-src 'self' data: https: blob:; frame-src 'self' https://accounts.google.com https://*.google.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://accounts.google.com https://apis.google.com https://*.gstatic.com; font-src 'self' https://*.gstatic.com data:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 